document.addEventListener('DOMContentLoaded',async()=>{const form=document.querySelector('#booking-form');if(!form)return;let boat;try{boat=await api(`/boats/${encodeURIComponent(query('boatId'))}?date=${encodeURIComponent(query('date')||'')}`)}catch(error){showError('#booking-error',error.message);form.querySelector('button[type="submit"]').disabled=true;return}
  const date=form.elements.travelDate;date.value=query('date')||'';date.min=new Date().toISOString().slice(0,10);const time=form.elements.time;if(/^\d{2}:\d{2}$/.test(boat.departure_time||''))time.value=boat.departure_time;
  const image=document.querySelector('#boat-image');image.src=boat.image;image.alt=boat.name;image.onerror=()=>{image.src='https://images.unsplash.com/photo-1505138180678-276b60fcbc4a?auto=format&fit=crop&w=900&q=80'};
  document.querySelector('#boat-name').textContent=boat.name;document.querySelector('#boat-route').textContent=boat.service_location||`${portLabel(boat.departure_port)} → ${portLabel(boat.destination)}`;document.querySelector('#trip-time').textContent=time.value||'เลือกเวลา';document.querySelector('#price-person').textContent=money(boat.price);
  let seats=boat.available_seats;const seatNode=document.querySelector('#boat-seats');const countField=form.elements.passengerCount;
  const update=()=>{countField.max=String(seats);if(Number(countField.value)>seats&&seats>0)countField.value=String(seats);const count=Number(countField.value||1);document.querySelector('#passenger-count').textContent=count;document.querySelector('#total-price').textContent=money(boat.price*count);document.querySelector('#trip-time').textContent=time.value||'เลือกเวลา';seatNode.textContent=`${seats} ที่`};
  const checkSeats=async()=>{if(!date.value)return;try{const current=await api(`/boats/${encodeURIComponent(boat.id)}?date=${encodeURIComponent(date.value)}`);seats=current.available_seats;update();if(seats<1)showError('#booking-error','วันที่เลือกไม่มีที่นั่งเหลือ กรุณาเลือกวันอื่น')}catch(error){showError('#booking-error',error.message)}};
  countField.addEventListener('change',update);time.addEventListener('change',update);date.addEventListener('change',checkSeats);update();if(date.value)await checkSeats();
  form.addEventListener('submit',async event=>{event.preventDefault();if(!form.reportValidity())return;if(Number(countField.value)>seats){showError('#booking-error',`วันที่เลือกเหลือที่นั่ง ${seats} ที่`);return}const button=form.querySelector('button[type="submit"]');button.disabled=true;button.textContent='กำลังบันทึกการจอง…';const data=Object.fromEntries(new FormData(form));try{const booking=await api('/bookings',{method:'POST',body:JSON.stringify({...data,boatId:boat.id,passengerCount:Number(data.passengerCount)})});sessionStorage.setItem('lastBooking',JSON.stringify(booking));location.href=`/pages/confirmation.html?id=${encodeURIComponent(booking.id)}`}catch(error){showError('#booking-error',error.message);button.disabled=false;button.textContent='ยืนยันการจอง'}});
});
