const dateText=value=>{if(!value)return '—';const [year,month,day]=String(value).split('-');return `${day}/${month}/${year}`};
const historyStatus=status=>status==='ยกเลิกแล้ว'||status==='cancelled'?'ยกเลิกแล้ว':'จองแล้ว';
async function renderBookingHistory(){
  const root=document.querySelector('#booking-history');if(!root)return;
  try{
    const bookings=await api('/bookings');
    if(!bookings.length){root.innerHTML='<div class="history-empty"><p>ยังไม่มีประวัติการจอง</p><a class="button" href="/pages/search.html">ไปดูเรือ</a></div>';return}
    root.innerHTML=`<div class="history-list">${bookings.map(booking=>{
      const cancelled=historyStatus(booking.status)==='ยกเลิกแล้ว',id=esc(booking.id),total=Number(booking.price||0)*Number(booking.passengerCount||1);
      return `<article class="booking-card" data-booking-id="${id}"><div class="booking-card-head"><img class="booking-card-image" src="${esc(booking.boatImage||'https://images.unsplash.com/photo-1505138180678-276b60fcbc4a?auto=format&fit=crop&w=900&q=80')}" alt="${esc(booking.boatName)}"><div class="booking-card-summary"><span class="booking-status ${cancelled?'cancelled':''}">${historyStatus(booking.status)}</span><h2>${esc(booking.bookingNumber||booking.id)}</h2><p>${esc(booking.boatName)}</p><p>ผู้จอง: ${esc(booking.customerName)} · ${esc(booking.phone)}</p><p>${dateText(booking.bookingDate)} · ${esc(booking.bookingTime)} · ${esc(booking.passengerCount)} คน</p><strong>${money(total)}</strong></div></div><div class="booking-card-actions"><button class="button secondary small history-details-button" type="button">ดูรายละเอียด</button>${cancelled?'':`<button class="button small cancel-booking-button" type="button">ยกเลิกการจอง</button>`}</div><div class="history-details hidden"><div class="summary-row"><span>หมายเลขการจอง</span><b>${esc(booking.bookingNumber||booking.id)}</b></div><div class="summary-row"><span>ชื่อเรือ</span><b>${esc(booking.boatName)}</b></div><div class="summary-row"><span>ชื่อผู้จอง</span><b>${esc(booking.customerName)}</b></div><div class="summary-row"><span>เบอร์โทรศัพท์</span><b>${esc(booking.phone)}</b></div><div class="summary-row"><span>วันที่</span><b>${dateText(booking.bookingDate)}</b></div><div class="summary-row"><span>เวลา</span><b>${esc(booking.bookingTime)}</b></div><div class="summary-row"><span>จำนวนผู้โดยสาร</span><b>${esc(booking.passengerCount)} คน</b></div><div class="summary-row"><span>ราคาต่อคน</span><b>${money(booking.price)}</b></div><div class="summary-row"><span>ราคารวม</span><b>${money(total)}</b></div><div class="summary-row"><span>หมายเหตุ</span><b>${esc(booking.note||'ไม่มี')}</b></div><div class="summary-row"><span>สถานะ</span><b>${historyStatus(booking.status)}</b></div><div class="summary-row"><span>วันที่สร้างรายการ</span><b>${esc(booking.createdAt||'—')}</b></div></div></article>`;
    }).join('')}</div>`;
    root.querySelectorAll('.history-details-button').forEach(button=>button.addEventListener('click',()=>{const details=button.closest('.booking-card').querySelector('.history-details');details.classList.toggle('hidden');button.textContent=details.classList.contains('hidden')?'ดูรายละเอียด':'ซ่อนรายละเอียด'}));
    root.querySelectorAll('.cancel-booking-button').forEach(button=>button.addEventListener('click',async()=>{const card=button.closest('.booking-card'),id=card.dataset.bookingId;if(!confirm(`ต้องการยกเลิกการจอง ${id} หรือไม่?`))return;try{await api(`/bookings/${encodeURIComponent(id)}`,{method:'PUT',body:JSON.stringify({status:'ยกเลิกแล้ว'})});await renderBookingHistory()}catch(error){showError(root,error.message)}}));
  }catch(error){showError(root,error.message)}
}
document.addEventListener('DOMContentLoaded',renderBookingHistory);
